# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cc3ecf7fe6cd384f750f1bcb3fa6d179c8ca735346172fa9a4eb3593d74f39b0e4aec96e46da0df923872cb3647020b2fb05272a7720458353b8c18a637b402

test:
  secret_key_base: e38895de40a72d241349662ac253b95cc05ed2683a1279f323a4ca1831a5d83f7ab9689494a988fc7c2de28b3987b1357dc7212bb9b6dafcd53a47c493ff1b6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
